#! /bin/sh

if [ $(id -u) != 0 ]; then
	echo "Insufficient privileges to setup site-settings."
	exit 1
fi

PREFIX=/usr/local

. $PREFIX/etc/gfarm-s3.conf

EDITOR=./xvi $PREFIX/bin/gfarm-s3-viusermap

users=$(cat $GFARMS3_LOCAL_USER_MAP | grep -v '^#' | awk -F : '{print $2}')
for u in $users; do usermod -a -G gfarms3 $u; done
