#! /bin/sh

python runminio.py \
	--bucket_rootdir="/home/hp120273/hpci005858/tmp/nas1" \
	--shared_dir="sss" \
	--address="127.0.0.1:9000" \
	--access_key="K4XcKzocrUhrnCAKrx2Z" \
	--secret_key="39e+URNfFv/CCgs4bYcBMusR7ngMLOxEf6cpXWpB"
