#! /bin/sh

set -o xtrace

ENDPOINT_URL=http://127.0.0.1:9000

MINIO_ACCESS_KEY=K4XcKzocrUhrnCAKrx2Z
MINIO_SECRET_KEY=$(<$HOME/.gfarm-s3/secret_key)

PROFILE=user1

mc config host add $PROFILE $ENDPOINT_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
mc admin trace -v -a $PROFILE
