#! /bin/sh

PREFIX=/usr/local
WSGI_USER=user2
WSGI_PORT=8000
GFARMS3_BIN=$PREFIX/bin
GFARMS3_APACHE_REWRITE_CONF=$PREFIX/var/gfarm-s3/rewrite.conf

sed -e 's|@PREFIX@|'"$PREFIX"'|' \
	-e 's|@WSGI_USER@|'"$WSGI_USER"'|' \
	-e 's|@GFARMS3_APACHE_REWRITE_CONF@|'"$GFARMS3_APACHE_REWRITE_CONF"'|' \
	-e 's|@GFARMS3_BIN@|'"$GFARMS3_BIN"'|' \
	-e 's|@WSGI_PORT@|'"$WSGI_PORT"'|'
