#! /bin/sh

cd /home/nis/work/w-router

timeout=86400
bind=:8001
threads=40
workers=40
gunicorn router:app \
	${bind:+--bind $bind} \
	${timeout:+--timeout $timeout} \
	${threads:+--threads $threads} \
	${workers:+--workers $workers} \
	--log-level=debug \
	--reload
