#! /bin/sh

#set -o xtrace

export AWS_PROFILE=user1

ENDPOINT_URL=https://192.168.224.11
ENDPOINT_URL=http://192.168.224.11

export PYTHONWARNINGS="ignore:Unverified HTTPS request"

NO_VERIFY_SSL=--no-verify-ssl
NO_VERIFY_SSL=

DEBUG=--debug
DEBUG=

default_test=test0
default_test=testC

vflag=0
vflag=1

. ./subr

date >/tmp/foo

testC() {
#	aws s3 ls        s3://
#	aws s3 ls        s3://
#	aws s3 ls        s3://sss
#	aws s3 ls        s3://sss/user2/
#	aws s3 ls        s3://mybucket
	aws s3 mb        s3://mybucket
#	aws s3 mb        s3://new4
#	aws s3 cp /tmp/foo        s3://new4/foo
	aws s3 cp /tmp/foo        s3://mybucket/foo
#	aws s3 ls        s3://sss/hpci001971/
#	aws s3 ls        s3://sss/hpci001971/tak/
#	aws s3 ls        s3://sss/hpci001971/non/
	aws s3 ls        s3://mybucket
#	aws s3 ls        s3://non
#	aws s3 cp        s3://sss/hpci001971/tak/foo /tmp/foo
#	aws s3 cp /tmp/foo        s3://sss/hpci001971/tak/foo
}

update_credentials() {
	cat /home/nis/.aws/credentials | sed 's/^/old: /'
	aws_access_key_id=K4XcKzocrUhrnCAKrx2Z
	aws_secret_access_key=$(ssh gfarm cat /home/user1/.gfarm-s3/secret_key)
	cat <<-EOF > /home/nis/.aws/credentials
	[user1]
	aws_access_key_id = $aws_access_key_id 
	aws_secret_access_key = $aws_secret_access_key 
	EOF
	cat /home/nis/.aws/credentials | sed 's/^/new: /'
}

sets3v4() {
	aws configure set default.s3.signature_version s3v4
}

test0() {
	sendfile=/home/nis/work/tmp/s/64M
#	aws s3 ls        s3://myb
#	aws s3 ls        s3://myb/
	aws s3 mb        s3://mybucket
#	time aws s3 cp k/foo  s3://mybucket/foo
#	time aws s3 cp        s3://mybucket/foo k/baz
	time aws s3 cp $sendfile   s3://mybucket/$(basename $sendfile)
#	aws s3 cp k/32M  s3://mybucket/32M
#	aws s3 cp k/7M   s3://mybucket/7M
#	aws s3 cp k/07M  s3://mybucket/07M
#	aws s3 ls        s3://mybucket
}

test1() {

	aws s3 cp        s3://mybucket/foo k/baz
	openssl sha1 -r k/foo k/baz
	aws s3 cp        s3://mybucket/64M k/baz
	openssl sha1 -r k/64M k/baz
	aws s3 cp        s3://mybucket/32M k/baz
	openssl sha1 -r k/32M k/baz
	aws s3 cp        s3://mybucket/7M k/baz
	openssl sha1 -r k/7M k/baz
	aws s3 cp        s3://mybucket/07M k/baz
	openssl sha1 -r k/07M k/baz

	rm k/baz
}

testA() {
	aws s3 ls        s3://

	aws s3 mb        s3://mybucket
	aws s3 mb        s3://sss

	aws s3 cp k/32M  s3://mybucket/myobject
	aws s3 cp k/32M  s3://sss/user2/herbucket/object1
	aws s3 cp k/32M  s3://sss/user2/herbucket/object2
	aws s3 cp k/32M  s3://sss/user2/herbucket/blob3
	aws s3 cp s3://sss/user2/herbucket/blob3/ s3://sss/user2/herbucket/blob4
	aws s3 cp s3://sss/user2/herbucket/ s3://sss/user2/xherbucket

	aws s3 ls        s3://
	aws s3 ls        s3://sss
	aws s3 ls        s3://sss/
	aws s3 ls        s3://sss/user2
	aws s3 ls        s3://sss/user2/
	aws s3 ls        s3://sss/user2/
	aws s3 ls        s3://sss/user2/herbucket
	aws s3 ls        s3://sss/user2/herbucket/

	aws s3 cp        s3://sss/user2/herbucket/blob3 k/bar
	openssl sha1 -r k/32M k/bar

	aws s3 rm        s3://sss/user2/herbucket/blob3
	aws s3 rm        s3://sss/user2/herbucket/object2
	aws s3 rm        s3://sss/user2/herbucket/object1
	aws s3 rm        s3://mybucket/myobject

	aws s3 rb        s3://sss
	aws s3 rb        s3://mybucket
}

testB() {
	aws s3 ls        s3://nonexistent/foo/bar
	aws s3 mb        s3://nonexistent/foo/bar
	aws s3 cp k/foo  s3://mybucket/aa/foo
	aws s3 cp k/foo  s3://mybucket/aa/bar
	aws s3 rm        s3://mybucket/aa/bar
	aws s3 cp k/foo  s3://mybucket/bar/foo
}

test_deeppath() {
	aws s3 mb        s3://sss/user2
	#aws s3 mb        s3://sss/user2	--- fail on client side
	aws s3 rb        s3://sss
}

test_mv() {
	aws s3 mb        s3://mybucket
	aws s3 cp k/foo  s3://mybucket/myobject
	aws s3 mv s3://mybucket/myobject s3://mybucket/myobject2
	aws s3 rm        s3://mybucket/myobject2
	aws s3 rm        s3://mybucket/myobject
	aws s3 rb        s3://mybucket
}

rm -f k/foo k/bar

cat <<EOF > k/foo
@@@@@ $(date)
EOF

if [ $# = 1 ]; then
	cmd="$1"
else
	cmd=$default_test
fi

case "$cmd" in
update_credentials|sets3v4|test0|testA|testB|test_deeppath|test_mv|testC)
	$cmd;;
*)
	echo "usage: $0 sets3v4|test0|testA|testB|test_deeppath|test_mv"
	exit 1;;
esac

exit 0
