#! /bin/sh

#set -o xtrace

PREFIX=/usr/local
USER1=user1
WEBUI_USER=user2
HTTPD_USER=apache

PKGCONFIG_D=/usr/local/share/pkgconfig
APACHE_DOCUMENTROOT=/usr/local/share/www

gen_conf() {
	local conffile="$1"
	shift
	rm -f "$conffile"
	sed < "$conffile".in > "$conffile" "$@"
	chmod a-w "$conffile"
}

install_if_differ() {
	if ! $3 cmp "$1" "$2"; then
		echo cp "$1" "$2"
		sudo cp "$1" "$2"
	fi
}

create_directory_unless_exists() {
	if [ ! -d "$1" ]; then
		echo mkdir -p "$1"
		sudo mkdir -p "$1"
	fi
}

create_empty_file_unless_exists() {
	if [ ! -e "$1" ]; then
		echo touch "$1"
		sudo touch "$1"
	fi
}

gen_conf gfarm-s3.conf -e 's@PREFIX@'"$PREFIX"''
. ./gfarm-s3.conf
install_if_differ gfarm-s3.conf $GFARMS3_CONF

create_directory_unless_exists $GFARMS3_METADIR

install_if_differ secret_key $GFARMS3_SECRET_KEY 

install_if_differ gfarm_s3_local_user_map $GFARMS3_LOCAL_USER_MAP
sudo chown $HTTPD_USER $GFARMS3_LOCAL_USER_MAP

gen_conf sudoers \
	-e 's@WEBUI_USER@'"$WEBUI_USER"'' \
	-e 's@HTTPD_USER@'"$HTTPD_USER"''
install_if_differ sudoers /etc/sudoers.d/gfarm-s3 sudo

create_directory_unless_exists $(dirname $GFARMS3_USER_PORT_MAP)
sudo chown $HTTPD_USER $(dirname $GFARMS3_USER_PORT_MAP)
create_empty_file_unless_exists $GFARMS3_USER_PORT_MAP
sudo chown $HTTPD_USER $GFARMS3_USER_PORT_MAP

install_if_differ gfarm.conf /etc/rsyslog.d/gfarm.conf

create_directory_unless_exists $PKGCONFIG_D
install_if_differ gfarm.pc $PKGCONFIG_D/gfarm.pc

if ! grep -q '^gfarms3:' /etc/group; then
	sudo groupadd gfarms3
fi
sudo usermod -a -G gfarms3 $USER1

create_directory_unless_exists $(dirname $GFARMS3_APACHE_REWRITE_CONF)
sudo chown $HTTPD_USER $(dirname $GFARMS3_APACHE_REWRITE_CONF)
create_empty_file_unless_exists $GFARMS3_APACHE_REWRITE_CONF
sudo chown $HTTPD_USER $GFARMS3_APACHE_REWRITE_CONF

create_directory_unless_exists $APACHE_DOCUMENTROOT
create_empty_file_unless_exists $APACHE_DOCUMENTROOT/index.html

gen_conf apache-gfarm-s3.conf \
	-e '/^[ 	]*#/d' \
	-e 's@DOCUMENTROOT@'"$APACHE_DOCUMENTROOT"'' \
	-e 's@GFARMS3_APACHE_REWRITE_CONF@'"$GFARMS3_APACHE_REWRITE_CONF"''
install_if_differ apache-gfarm-s3.conf $GFARMS3_APACHE_REWRITE_MASTER_CONF

sudo systemctl enable httpd
sudo systemctl start httpd
sudo chmod og+rX /var/log/httpd

(mod_wsgi-express module-config;
 cat apache-gfarm-s3-wsgi.conf.in) > apache-gfarm-s3-wsgi.conf
install_if_differ apache-gfarm-s3-wsgi.conf $GFARMS3_APACHE_REWRITE_WSGI_CONF

SYS_HTTPD_CONF=/etc/httpd/conf/httpd.conf
sed < $SYS_HTTPD_CONF \
	-e '/^User /s.*User '"$HTTPD_USER"'' \
	-e '/^Group /s.*Group '"$HTTPD_USER"'' > httpd.conf
install_if_differ httpd.conf $SYS_HTTPD_CONF
