#! /bin/sh

#set -o xtrace

PREFIX=/usr/local
USER1=user1
WEBUI_USER=user2

PKGCONFIG_D=/usr/local/share/pkgconfig
APACHE_DOCUMENTROOT=/usr/local/share/www

check_n_install() {
	if ! cmp "$1" "$2"; then
		echo cp "$1" "$2"
		sudo cp "$1" "$2"
	fi
}

check_n_create_dir() {
	if [ ! -d "$1" ]; then
		echo mkdir -p "$1"
		sudo mkdir -p "$1"
		if [ $# = 2 ]; then
			echo chown "$2" "$1"
			sudo chown "$2" "$1"
		fi
	fi
}

check_n_create_empty_file() {
	if [ ! -e "$1" ]; then
		echo touch "$1"
		sudo touch "$1"
		if [ $# = 2 ]; then
			echo chown "$2" "$1"
			sudo chown "$2" "$1"
		fi
	fi
}

gen_conf() {
	local conffile="$1"
	shift
	rm -f "$conffile"
	sed < "$conffile".in > "$conffile" "$@"
	chmod a-w "$conffile"
}

gen_conf gfarm-s3.conf -e 's@PREFIX@'"$PREFIX"''

. ./gfarm-s3.conf

gen_conf apache-gfarm-s3.conf \
	-e '/^[ 	]*#/d' \
	-e 's@DOCUMENTROOT@'"$APACHE_DOCUMENTROOT"'' \
	-e 's@GFARMS3_APACHE_REWRITE_CONF@'"$GFARMS3_APACHE_REWRITE_CONF"''

check_n_create_dir $GFARMS3_METADIR

check_n_install gfarm-s3.conf /usr/local/etc/gfarm-s3.conf

check_n_install secret_key $GFARMS3_SECRET_KEY 

check_n_install gfarm_s3_local_user_map $GFARMS3_LOCAL_USER_MAP

check_n_install sudoers /etc/sudoers.d/gfarm-s3

check_n_create_dir $(dirname $GFARMS3_USER_PORT_MAP ) $WEBUI_USER
check_n_create_empty_file $GFARMS3_USER_PORT_MAP $WEBUI_USER

check_n_install gfarm.conf /etc/rsyslog.d/gfarm.conf

check_n_create_dir $PKGCONFIG_D
check_n_install gfarm.pc $PKGCONFIG_D/gfarm.pc

sudo chown $WEBUI_USER /usr/local/etc/gfarm_s3_local_user_map

sudo groupadd gfarms3
sudo usermod -a -G gfarms3 $USER1

check_n_create_dir $(dirname $GFARMS3_APACHE_REWRITE_CONF) $WEBUI_USER
check_n_create_empty_file $GFARMS3_APACHE_REWRITE_CONF $WEBUI_USER

check_n_create_dir $APACHE_DOCUMENTROOT
check_n_create_empty_file $APACHE_DOCUMENTROOT/index.html

check_n_install apache-gfarm-s3.conf $GFARMS3_APACHE_REWRITE_MASTER_CONF

sudo systemctl enable httpd
sudo systemctl start httpd
sudo chmod og+rX /var/log/httpd
