version: '3.4'

# use variables from .env

services:
  gfminio:
    hostname: gfminio
    build:
      context: ../
      dockerfile: ./docker/gfminio/Dockerfile
      args:
        - GFARM_SRC_URL=https://github.com/oss-tsukuba/gfarm/archive/refs/tags/2.7.19.tar.gz
        - GFARM2FS_SRC_URL=https://github.com/oss-tsukuba/gfarm2fs/archive/refs/tags/1.2.15.tar.gz
        ### optional
        - http_proxy=${http_proxy:-}
        - https_proxy=${https_proxy:-}
    environment:
      ### mandatory
      - SERVER_URL=${SERVER_URL:?SERVER_URL}

      ### optional
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      # empty means using SERVER_NAME from SERVER_URL
      - ALLOWED_HOSTS=${ALLOWED_HOSTS-*}
      # empty means using SERVER_URL
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS-}

      ### TODO MYPROXY_SERVERS=
      - MYPROXY_SERVER=
      - GFARM_S3_BUILD_DIR=/build_cache
      - GFARM_S3_SHARED_DIR=/share
      - GFARM_S3_USERNAME=_gfarm_s3
      - GFARM_S3_GROUPNAME=_gfarm_s3
      ### TODO GFARM_S3_LOCALTMP
      - CACHE_DIR=/var/cache/gfarm-s3
      - CACHE_SIZE=1024

    volumes:
      #TODO supervisord
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      - /home:/host_home:ro
      - s3secret:/s3secret:rw
      - build_cache:/build_cache:rw

      - ./mnt:/mnt:rw

      - ./gfarm2.conf:/usr/local/etc/gfarm2.conf:ro
      - ./certificates:/etc/grid-security/certificates:ro
      - ./gfarm-s3-usermap.conf:/gfarm-s3-usermap.conf:ro

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    privileged: false
    ports:
      - 61080:80
      - 61443:443

volumes:
  s3secret:
  build_cache:
