version: '3'

# use variables from .env

services:
  gfminio:
    hostname: gfminio
    privileged: false
    build:
      context: ../
      dockerfile: ./docker/gfminio/Dockerfile
      args:
        #- GFARM_SRC_URL=${GFARM_SRC_URL:-https://github.com/oss-tsukuba/gfarm/archive/refs/tags/2.7.19.tar.gz}
        - GFARM_SRC_GIT_URL=${GFARM_SRC_GIT_UR:-https://github.com/oss-tsukuba/gfarm.git}
        - GFARM_SRC_GIT_BRANCH=${GFARM_SRC_GIT_BRANCH:-2.7}
        ### optional
        - http_proxy=${http_proxy:-}
        - https_proxy=${https_proxy:-}
    environment:
      ### mandatory
      - SERVER_URL=${SERVER_URL:?SERVER_URL}

      ### optional
      - DEBUG=${DEBUG:-0}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}

      - TZ=${TZ:-Asia/Tokyo}
      - http_proxy=${http_proxy:-}
      - https_proxy=${https_proxy:-}
      - GFARM_S3_MINIO_SRC_GIT_URL=${GFARM_S3_MINIO_SRC_GIT_URL:-https://github.com/oss-tsukuba/gfarm-s3-minio.git}
      #TODO change to master branch
      - GFARM_S3_MINIO_SRC_GIT_BRANCH=${GFARM_S3_MINIO_SRC_GIT_BRANCH:-gfarmmerge}

      # empty means using SERVER_NAME from SERVER_URL
      - ALLOWED_HOSTS=${ALLOWED_HOSTS-*}
      # empty means using SERVER_URL
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS-}

      - MYPROXY_SERVER=
      - GFARM_S3_BUILD_DIR=/build_cache
      - GFARM_S3_SHARED_DIR=/share
      - GFARM_S3_USERNAME=_gfarm_s3
      - GFARM_S3_GROUPNAME=_gfarm_s3
      - CACHE_DIR=/var/cache/gfarm-s3
      - CACHE_SIZE=1024

    volumes:
      - copy_home:/home:rw
      - build_cache:/build_cache:rw

      # /dev/null means downloading from GFARM_S3_MINIO_SRC_GIT_URL
      - ${GFARM_S3_MINIO_SRC_DIR:-/dev/null}:/gfarm-s3-minio

      #TODO  ${SHARE_HOSTDIR:-/dev/null}:/share_host
      - ./mnt:/mnt:rw

      #TODO
      - ./gfarm2.conf:/usr/local/etc/gfarm2.conf:ro
      - ./certificates:/etc/grid-security/certificates:ro
      - ./gfarm-s3-usermap.conf:/gfarm-s3-usermap.conf:ro

  copy_home:
    hostname: copy_home
    build:
      context: ./copy_home/
      args:
        - http_proxy=${http_proxy:-}
        - https_proxy=${https_proxy:-}
    volumes:
      - /home:/host_home:ro
      - copy_home:/copy_home:rw
      - ./mnt:/mnt:rw

volumes:
  copy_home:
  build_cache:
