version: '3.4'

# variables from .env

services:
  gfminio:
    environment:
      - VIRTUAL_HOST=${SERVER_NAME}
      - MYPROXY_SERVER=portal.hpci.nii.ac.jp:7512
      #- MYPROXY_SERVER=portal-c.hpci.nii.ac.jp:7512
      #- GFARM_S3_SHARED_DIR=/home/hp...../hpci...../minio-share
      - GFARM_S3_SHARED_DIR=${GFARM_S3_SHARED_DIR}
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    ports:
      - ${HTTP_PORT:-80}:${HTTP_PORT:-80}
      - ${HTTPS_PORT:-443}:${HTTPS_PORT:-443}
    environment:
      - DEFAULT_HOST=${SERVER_NAME}
      - HTTP_PORT=${HTTP_PORT:-80}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - HTTPS_METHOD=noredirect
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - proxy-tier

  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    environment:
      - SSL_SUBJECT=${SERVER_NAME}
      - CA_SUBJECT=ca@nextcloud-gfarm.example.com
      - SSL_KEY=/certs/${SERVER_NAME}.key
      - SSL_CSR=/certs/${SERVER_NAME}.csr
      - SSL_CERT=/certs/${SERVER_NAME}.crt
      - SSL_DNS=${SERVER_NAME}
    volumes:
      - certs:/certs

volumes:
  html:
  certs:

networks:
  proxy-tier:
