version: '3.4'

# variables from .env

services:
  gfminio:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - MYPROXY_SERVER=portal.hpci.nii.ac.jp:7512
      #- MYPROXY_SERVER=portal-c.hpci.nii.ac.jp:7512
      #- GFARM_S3_SHARED_DIR=/home/hp...../hpci...../minio-share
      - GFARM_S3_SHARED_DIR=${GFARM_S3_SHARED_DIR}
