version: '3.4'

# variables from .env

services:
  gfminio:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      #- MYPROXY_SERVER=portal.hpci.nii.ac.jp:7512
      #- MYPROXY_SERVER=portal-c.hpci.nii.ac.jp:7512
      #- GFARM_S3_SHARED_DIR=/home/hp...../hpci...../minio-share
      - GFARM_S3_SHARED_DIR=/share
    volumes:
      - /work/gfarm/docker/dev/mnt:/mnt2:ro
      - /work/gfarm/docker/dev/mnt/COPY_DIR/HOMES:/host_home:ro
      - /work/gfarm/docker/dev/mnt/COPY_DIR/gfarm2.conf:/usr/local/etc/gfarm2.conf:ro
      - /work/gfarm/docker/dev/mnt/COPY_DIR/CERTS:/etc/grid-security/certificates:ro
      - /work/gfarm/docker/dev/mnt/COPY_DIR/gfarm-s3-usermap.conf:/gfarm-s3-usermap.conf:ro
    networks:
      gfarm_dev:
        #ipv4_address: 10.2.3.100

networks:
  gfarm_dev:
    external: true
