#! /bin/sh

set -o xtrace

mv $HOME/.globus $HOME/.globus-local
mkdir -p $HOME/.globus-hpci/certificates
ln -s $HOME/.globus-hpci $HOME/.globus

(
cd $HOME/.globus-hpci/certificates
curl -o hpcica.pem.zip https://www.hpci.nii.ac.jp/ca/hpcica.pem.zip
curl -o hpcica.signing_policy.zip https://www.hpci.nii.ac.jp/ca/hpcica.signing_policy.zip
unzip hpcica.pem.zip
unzip hpcica.signing_policy.zip

curl -o $HOME/.gfarm2rc https://www.hpci-office.jp/info/download/attachments/69471402/gfarm2.conf

cat << 'EOF' > getcrl.sh
cd ~/.globus-hpci/certificates
curl -o hpcica.crl https://www.hpci.nii.ac.jp/ca/hpcica.crl
mv hpcica.crl `openssl crl -in hpcica.crl -noout -hash`.r0
EOF

chmod +x getcrl.sh
./getcrl.sh
)
