#! /bin/sh
#sudo yum update -y
sudo yum install -y myproxy
sudo yum install -y httpd
sudo yum install -y mod_ssl
sudo yum install -y uuid
sudo yum install -y python3-devel
sudo yum install -y rsyslog

GFARMS3CONF=/etc/httpd/conf.d/gfarm-s3.conf
REWRITECONF=/usr/local/var/gfarm-s3/rewrite.conf
DOCUMENTROOT=/home/user1/work/s3g/www
sudo mkdir -p $(dirname $REWRITECONF)
sudo chown user2 $(dirname $REWRITECONF)
sudo touch $REWRITECONF
sudo chown user2 $REWRITECONF

if [ ! -e $GFARMS3CONF ]; then
cat <<EOF | grep -v '^[ 	]*#' | sudo dd of=$GFARMS3CONF
ServerName 192.168.224.22
<VirtualHost *:80>
#<VirtualHost *:443>
#	SSLEngine on
#	SSLCertificateFile /home/user1/work/s3g/etc/server.crt
#	SSLCertificateKeyFile /home/user1/work/s3g/etc/server.key

	DocumentRoot "$DOCUMENTROOT"
	ServerAdmin root@localhost
	CustomLog logs/access_log common
	ErrorLog logs/error_log
#	LogLevel debug rewrite:trace8
#	LogLevel debug trace8

	RewriteEngine on

	Include $REWRITECONF

	ProxyPreserveHost on
	ProxyAddHeaders off

	<Directory "$DOCUMENTROOT">
		AllowOverride FileInfo AuthConfig Limit Indexes
		Options MultiViews Indexes SymLinksIfOwnerMatch Includes
		AllowOverride All
		Require all granted 
	</Directory>

</VirtualHost>
EOF
fi

if [ ! -e $REWRITECONF ]; then
	sudo touch $REWRITECONF
fi

sudo systemctl enable httpd
sudo systemctl start httpd
sudo chmod og+rX /var/log/httpd

sudo yum install -y python2-pip
sudo pip install boto3
