#! /bin/sh
if [ $(id -u) != 0 ]; then
	echo "Insufficient privileges to install prerequisites."
	exit 1
fi
yum update -y
yum install -y httpd
yum install -y mod_ssl
yum install -y uuid
yum install -y myproxy
yum install -y python3-devel
yum install -y python3-pip
#yum install -y nginx

python3 -m pip install 'Django<2.2'
python3 -m pip install gunicorn

## debug
python3 -m pip install boto3
