#! /bin/sh

set -o xtrace

export GLOBUS_GSSAPI_NAME_COMPATIBILITY="HYBRID"

G=$(gfgroup -l | grep hpci001971  | awk -F: '{ print $1 }')
#G=hp120273
#D=/gfarm/hp120273
D=/gfarm/$G

echo $D
[ -e $D/user1 ] || sudo mkdir -p $D/user1
sudo chmod 755 $D
sudo chown user1 $D/user1

mount.hpci
