#! /bin/sh

if [ $(id -u) != 0 ]; then
	echo "Insufficient privileges to setup site-settings."
	exit 1
fi

HTTPD_CONF_D=/etc/httpd/conf.d
HTTPD_DocumentRoot=/usr/local/share/www
SERVER_CRT=/etc/httpd/conf/ssl.key/server.crt
SERVER_KEY=/etc/httpd/conf/ssl.crt/server.key

sed < etc/myserver.conf.in > $HTTPD_CONF_D/myserver.conf \
	-e "s@DocumentRoot@$HTTPD_DocumentRoot"  \
	-e "s@SERVER_CRT@$SERVER_CRT" \
	-e "s@SERVER_KEY@$SERVER_KEY"

mkdir -p $HTTPD_DocumentRoot
mkdir -p $(dirname $SERVER_CRT)
mkdir -p $(dirname $SERVER_KEY)
echo "gfarm -- $(date)" > $HTTPD_DocumentRoot/index.html
cp etc/server.crt $SERVER_CRT
cp etc/server.key $SERVER_KEY

chmod og+rX /var/log/httpd

systemctl enable httpd
systemctl stop httpd
systemctl start httpd
