#! /bin/sh

. /usr/local/etc/gfarm-s3.conf

go_archive=go1.15.linux-amd64.tar.gz
mc_git=https://github.com/minio/mc.git
minio_git=git@github.com:oss-tsukuba/gfarm-s3-minio.git
go_url=https://dl.google.com/go/$go_archive

BUILDDIR=$HOME/build

export GOPATH=$BUILDDIR/go
export GOBIN=$GOPATH/bin

[ -d $BUILDDIR ] || mkdir -p $BUILDDIR

[ -d $BUILDDIR/go ] || (cd $BUILDDIR && curl $go_url | tar xfzp -)

PATH=$BUILDDIR/go/bin:$PATH

[ -d $BUILDDIR/mc ] || (cd $BUILDDIR && git clone $mc_git)
(cd $BUILDDIR/mc && go install)

[ -d $BUILDDIR/gfarm-s3-minio ] || (cd $BUILDDIR && git clone $minio_git)
(cd $BUILDDIR/gfarm-s3-minio && git checkout gatewaygfarm)

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig 
export CGO_LDFLAGS=-Wl,-rpath,/usr/local/lib

(cd $BUILDDIR/gfarm-s3-minio && go install)
