#! /bin/sh

##gfarm2fs の configure
##--with-gfarm=/usr/local
##--prefix=/usr/local

srcdir=/home/user1/work/gfarm-s3-minio-web

with_gfarm=/usr/local
prefix=/usr/local
BUILDDIR=$srcdir/minio/tmp/build

. /usr/local/etc/gfarm-s3.conf

mc_git=https://github.com/minio/mc.git
minio_git=git@github.com:oss-tsukuba/gfarm-s3-minio.git

[ -d $BUILDDIR ] || mkdir -p $BUILDDIR

[ -d $BUILDDIR/mc ] || (cd $BUILDDIR && git clone $mc_git)

[ -d $BUILDDIR/gfarm-s3-minio ] || (cd $BUILDDIR && git clone $minio_git &&
	cd gfarm-s3-minio && git checkout gatewaygfarm)

export GOPATH=$srcdir/minio/tmp/go
export GOBIN=$GOPATH/bin
PATH=/usr/local/go/bin:$PATH

(cd $BUILDDIR/mc && $GOPATH/bin/go install)

if [ x"$with_gfarm" = x"/usr" ]; then with_gfarm=; fi

(cd $BUILDDIR/gfarm-s3-minio && 
 ${with_gfarm:+CGO_LDFLAGS=-Wl,-rpath,$with_gfarm/lib} \
 PKG_CONFIG_PATH=$with_gfarm/lib/pkgconfig $GOPATH/bin/go install)

file $GOBIN/mc
file $GOBIN/minio
